services:
    caddy:
        build: .
        restart: unless-stopped
        environment:
            PREVIEW_DOMAIN: ${PREVIEW_DOMAIN}
            PREVIEW_SLUG: ${PREVIEW_SLUG}
        ports:
            - "127.0.0.1:${PREVIEW_PORT}:80"
